const bcrypt = require('bcryptjs');
const { PrismaClient, CompanyStatus, JobCategory, JobModality, UserRole } = require('@prisma/client');

const prisma = new PrismaClient();

const companies = [
  {
    slug: 'techvision-inc',
    name: 'TechVision Inc',
    logo: 'https://images.unsplash.com/photo-1718220216044-006f43e3a9b1?w=200&h=200&fit=crop',
    banner: 'https://images.unsplash.com/photo-1665360755361-d8cd03c82b28?w=1400&h=400&fit=crop',
    tagline: 'Liderando el futuro de la IA y el aprendizaje automatico',
    description: 'Empresa lider en innovacion tecnologica y desarrollo de IA.',
    culture:
      'Cultura de innovacion, colaboracion y aprendizaje continuo con horarios flexibles y mentoria personalizada.',
    location: 'Madrid',
    size: '500-1000 empleados',
    website: 'https://www.techvision.com',
    industry: 'Inteligencia Artificial',
    foundedYear: 2015,
    tags: ['Tecnologia', 'Remoto', 'Flexible'],
    benefits: [
      'Apoyo economico competitivo',
      'Mentoria personalizada',
      'Horarios flexibles',
      'Trabajo remoto o hibrido',
      'Capacitacion y certificaciones',
      'Oportunidad de contratacion',
    ],
    gallery: [
      'https://images.unsplash.com/photo-1718220216044-006f43e3a9b1?w=600&h=400&fit=crop',
      'https://images.unsplash.com/photo-1665360755361-d8cd03c82b28?w=600&h=400&fit=crop',
    ],
  },
  {
    slug: 'growthlabs',
    name: 'GrowthLabs',
    logo: 'https://images.unsplash.com/photo-1665360755361-d8cd03c82b28?w=200&h=200&fit=crop',
    banner: 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?w=1400&h=400&fit=crop',
    tagline: 'Startup en crecimiento con ambiente innovador',
    description: 'Startup enfocada en crecimiento digital, producto y marketing.',
    culture: 'Equipos pequenos, autonomia alta y aprendizaje muy practico.',
    location: 'Valencia',
    size: '50-100 empleados',
    website: 'https://www.growthlabs.example',
    industry: 'Marketing y producto digital',
    foundedYear: 2020,
    tags: ['Startup', 'Marketing', 'Hibrido'],
    benefits: ['Horario flexible', 'Mentoria', 'Ambiente dinamico'],
    gallery: [],
  },
  {
    slug: 'cloudscale',
    name: 'CloudScale',
    logo: 'https://images.unsplash.com/photo-1496180470114-6ef490f3ff22?w=200&h=200&fit=crop',
    banner: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1400&h=400&fit=crop',
    tagline: 'Soluciones empresariales en la nube',
    description: 'Consultora especializada en cloud, DevOps y operaciones de infraestructura.',
    culture: 'Aprendizaje tecnico intensivo, colaboracion remota y cultura de mejora continua.',
    location: 'Malaga',
    size: '100-250 empleados',
    website: 'https://www.cloudscale.example',
    industry: 'Cloud',
    foundedYear: 2018,
    tags: ['Cloud', 'Desarrollo', 'Remoto'],
    benefits: ['Certificaciones cloud', 'Trabajo remoto', 'Mentoria tecnica'],
    gallery: [],
  },
  {
    slug: 'designstudio',
    name: 'DesignStudio',
    logo: 'https://images.unsplash.com/photo-1510832758362-af875829efcf?w=200&h=200&fit=crop',
    banner: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=1400&h=400&fit=crop',
    tagline: 'Experiencias digitales con foco en diseno',
    description: 'Agencia creativa especializada en branding, producto y experiencias digitales.',
    culture: 'Ambiente creativo, feedback constante y proyectos con clientes reales.',
    location: 'Barcelona',
    size: '25-50 empleados',
    website: 'https://www.designstudio.example',
    industry: 'Diseno digital',
    foundedYear: 2019,
    tags: ['Diseno', 'Creativo', 'Presencial'],
    benefits: ['Portfolio real', 'Mentoria UX', 'Equipo creativo'],
    gallery: [],
  },
];

const jobs = [
  {
    slug: 'practica-product-management-techvision',
    companySlug: 'techvision-inc',
    title: 'Practica en Product Management',
    description:
      'Participa en la definicion y mejora de productos digitales basados en IA junto a equipos multidisciplinares.',
    overview:
      'Buscamos un estudiante apasionado por la tecnologia y el producto para colaborar en proyectos reales de IA.',
    location: 'Remoto',
    modality: JobModality.REMOTE,
    duration: '6 meses',
    salaryLabel: '800 EUR/mes',
    schedule: 'Lunes a viernes, 20 horas semanales',
    startDate: 'Septiembre 2026',
    applicationDeadline: new Date('2026-08-15T23:59:59.000Z'),
    openings: 2,
    applicantsCount: 24,
    featured: true,
    tags: ['Producto', 'Remoto', 'Ingenieria'],
    responsibilities: [
      'Colaborar en roadmaps de producto',
      'Realizar investigacion de usuarios',
      'Apoyar en user stories y wireframes',
      'Analizar metricas de producto',
    ],
    requirements: [
      'Estudiante de ingenieria, informatica o similar',
      'Interes por tecnologia y producto',
      'Comunicacion clara y trabajo en equipo',
    ],
    benefits: ['Mentoria personalizada', 'Horario flexible', 'Trabajo remoto'],
    skills: ['Pensamiento analitico', 'Comunicacion', 'Figma basico'],
  },
  {
    slug: 'desarrollador-full-stack-junior-growthlabs',
    companySlug: 'growthlabs',
    title: 'Desarrollador Full Stack Junior',
    description: 'Construye funcionalidades web con React, Node.js y buenas practicas de producto.',
    overview: 'Practica tecnica para estudiantes que quieren crecer en desarrollo web fullstack.',
    location: 'Madrid',
    modality: JobModality.HYBRID,
    duration: '4 meses',
    salaryLabel: '700 EUR/mes',
    schedule: '20 horas semanales',
    startDate: 'Octubre 2026',
    applicationDeadline: new Date('2026-09-15T23:59:59.000Z'),
    openings: 1,
    applicantsCount: 18,
    featured: false,
    tags: ['Desarrollo', 'JavaScript', 'React'],
    responsibilities: ['Crear componentes React', 'Apoyar endpoints backend', 'Participar en code reviews'],
    requirements: ['Conocimientos basicos de JavaScript', 'Git basico', 'Ganas de aprender'],
    benefits: ['Mentoria tecnica', 'Proyectos reales', 'Posibilidad de continuidad'],
    skills: ['React', 'Node.js', 'SQL'],
  },
  {
    slug: 'disenador-ux-ui-practicas-designstudio',
    companySlug: 'designstudio',
    title: 'Disenador UX/UI en Practicas',
    description: 'Apoya procesos de investigacion, wireframes y diseno visual para productos digitales.',
    overview: 'Practica orientada a estudiantes con sensibilidad visual y curiosidad por producto.',
    location: 'Barcelona',
    modality: JobModality.ONSITE,
    duration: '6 meses',
    salaryLabel: '750 EUR/mes',
    schedule: 'Media jornada',
    startDate: 'Septiembre 2026',
    applicationDeadline: new Date('2026-08-30T23:59:59.000Z'),
    openings: 1,
    applicantsCount: 31,
    featured: true,
    tags: ['Diseno', 'UX', 'Figma'],
    responsibilities: ['Crear wireframes', 'Preparar prototipos', 'Apoyar research con usuarios'],
    requirements: ['Portfolio academico o personal', 'Figma basico', 'Interes por UX'],
    benefits: ['Portfolio real', 'Feedback semanal', 'Contacto con clientes'],
    skills: ['Figma', 'UX Research', 'Prototipado'],
  },
  {
    slug: 'practica-devops-cloudscale',
    companySlug: 'cloudscale',
    title: 'Practica en DevOps',
    description: 'Aprende fundamentos de automatizacion, despliegue e infraestructura cloud.',
    overview: 'Practica tecnica para estudiantes interesados en cloud, Linux y automatizacion.',
    location: 'Remoto',
    modality: JobModality.REMOTE,
    duration: '5 meses',
    salaryLabel: '750 EUR/mes',
    schedule: '20 horas semanales',
    startDate: 'Noviembre 2026',
    applicationDeadline: new Date('2026-10-10T23:59:59.000Z'),
    openings: 2,
    applicantsCount: 15,
    featured: false,
    tags: ['DevOps', 'AWS', 'Linux'],
    responsibilities: ['Apoyar pipelines CI/CD', 'Documentar procesos', 'Monitorizar servicios'],
    requirements: ['Linux basico', 'Interes por cloud', 'Git basico'],
    benefits: ['Certificaciones', 'Mentoria senior', 'Trabajo remoto'],
    skills: ['Linux', 'CI/CD', 'Cloud'],
  },
];

const unsplashImage = (photoId, width, height) =>
  `https://images.unsplash.com/${photoId}?w=${width}&h=${height}&fit=crop`;

const additionalCompanySeeds = [
  {
    slug: 'datanova-analytics',
    name: 'DataNova Analytics',
    logoPhoto: 'photo-1551288049-bebda4e38f71',
    bannerPhoto: 'photo-1551434678-e076c223a692',
    tagline: 'Datos claros para tomar mejores decisiones',
    description: 'Consultora especializada en analitica de datos, cuadros de mando y modelos predictivos.',
    culture: 'Equipo muy practico, revisiones semanales y aprendizaje guiado con datos reales.',
    location: 'Sevilla',
    size: '50-100 empleados',
    website: 'https://www.datanova.example',
    industry: 'Analitica de datos',
    foundedYear: 2019,
    tags: ['Datos', 'BI', 'Hibrido'],
    benefits: ['Mentoria en datos', 'Formacion en herramientas BI', 'Horario flexible'],
    jobs: [
      {
        slug: 'analista-datos-practicas-datanova',
        title: 'Analista de Datos en Practicas',
        description: 'Apoya al equipo en limpieza, analisis y visualizacion de datos de negocio.',
        overview: 'Practica para estudiantes que quieren aprender analitica aplicada en proyectos reales.',
        modality: JobModality.HYBRID,
        tags: ['Datos', 'SQL', 'Power BI'],
        skills: ['SQL', 'Power BI', 'Excel'],
        applicantsCount: 12,
        featured: true,
      },
      {
        slug: 'tecnico-bi-dashboard-datanova',
        title: 'Tecnico BI Junior en Practicas',
        description: 'Crea dashboards sencillos y documenta metricas clave para clientes.',
        overview: 'Rol orientado a reporting, visualizacion y seguimiento de indicadores.',
        modality: JobModality.HYBRID,
        tags: ['BI', 'Dashboards', 'Reporting'],
        skills: ['Power BI', 'Looker Studio', 'Analisis'],
        applicantsCount: 9,
      },
    ],
  },
  {
    slug: 'edunext-academy',
    name: 'EduNext Academy',
    logoPhoto: 'photo-1503676260728-1c00da094a0b',
    bannerPhoto: 'photo-1522202176988-66273c2fd55f',
    tagline: 'Tecnologia educativa para aprender mejor',
    description: 'Plataforma edtech que crea experiencias digitales de aprendizaje para centros y empresas.',
    culture: 'Ambiente cercano, feedback constante y foco en producto educativo accesible.',
    location: 'Madrid',
    size: '25-50 empleados',
    website: 'https://www.edunext.example',
    industry: 'EdTech',
    foundedYear: 2021,
    tags: ['Educacion', 'Producto', 'Remoto'],
    benefits: ['Formacion continua', 'Mentoria de producto', 'Trabajo hibrido'],
    jobs: [
      {
        slug: 'desarrollador-elearning-edunext',
        title: 'Desarrollador E-learning en Practicas',
        description: 'Desarrolla componentes para cursos online, formularios y seguimiento de progreso.',
        overview: 'Practica para aprender desarrollo frontend aplicado a educacion digital.',
        modality: JobModality.REMOTE,
        tags: ['React', 'E-learning', 'Frontend'],
        skills: ['React', 'JavaScript', 'HTML'],
        applicantsCount: 16,
      },
      {
        slug: 'asistente-contenido-digital-edunext',
        title: 'Asistente de Contenido Digital',
        description: 'Ayuda a preparar materiales interactivos, recursos visuales y pruebas de contenido.',
        overview: 'Rol ideal para perfiles creativos con interes en formacion y experiencia de usuario.',
        modality: JobModality.HYBRID,
        tags: ['Contenido', 'UX', 'Educacion'],
        skills: ['Canva', 'Redaccion', 'UX basico'],
        applicantsCount: 8,
      },
    ],
  },
  {
    slug: 'finflow-payments',
    name: 'FinFlow Payments',
    logoPhoto: 'photo-1563986768494-4dee2763ff3f',
    bannerPhoto: 'photo-1554224155-6726b3ff858f',
    tagline: 'Pagos digitales simples y seguros',
    description: 'Fintech que desarrolla soluciones de pagos, facturacion y conciliacion para pymes.',
    culture: 'Entorno exigente pero acompanado, con mucha atencion a calidad y seguridad.',
    location: 'Barcelona',
    size: '100-250 empleados',
    website: 'https://www.finflow.example',
    industry: 'FinTech',
    foundedYear: 2017,
    tags: ['Finanzas', 'Backend', 'Seguridad'],
    benefits: ['Mentoria tecnica', 'Formacion en producto fintech', 'Horario flexible'],
    jobs: [
      {
        slug: 'frontend-fintech-practicas-finflow',
        title: 'Frontend Fintech en Practicas',
        description: 'Participa en interfaces para pagos, paneles de cliente y formularios seguros.',
        overview: 'Practica para aprender frontend profesional en un entorno fintech.',
        modality: JobModality.HYBRID,
        tags: ['Frontend', 'React', 'Fintech'],
        skills: ['React', 'TypeScript', 'CSS'],
        applicantsCount: 19,
        featured: true,
      },
      {
        slug: 'qa-fintech-practicas-finflow',
        title: 'QA Tester Fintech Junior',
        description: 'Apoya pruebas funcionales y documentacion de incidencias en flujos de pago.',
        overview: 'Rol para estudiantes interesados en calidad de software y procesos criticos.',
        modality: JobModality.HYBRID,
        tags: ['QA', 'Testing', 'Pagos'],
        skills: ['Testing', 'Postman', 'Jira'],
        applicantsCount: 11,
      },
    ],
  },
  {
    slug: 'healthsync-digital',
    name: 'HealthSync Digital',
    logoPhoto: 'photo-1576091160399-112ba8d25d1d',
    bannerPhoto: 'photo-1505751172876-fa1923c5c528',
    tagline: 'Software sanitario centrado en las personas',
    description: 'Healthtech que conecta clinicas, pacientes y equipos medicos mediante herramientas digitales.',
    culture: 'Cultura responsable, documentacion clara y especial cuidado por la privacidad.',
    location: 'Valencia',
    size: '50-100 empleados',
    website: 'https://www.healthsync.example',
    industry: 'HealthTech',
    foundedYear: 2020,
    tags: ['Salud', 'UX', 'Backend'],
    benefits: ['Mentoria senior', 'Formacion en privacidad', 'Trabajo hibrido'],
    jobs: [
      {
        slug: 'backend-healthtech-practicas-healthsync',
        title: 'Backend HealthTech en Practicas',
        description: 'Apoya endpoints internos, integraciones y documentacion tecnica de servicios sanitarios.',
        overview: 'Practica tecnica enfocada en backend y buenas practicas de datos sensibles.',
        modality: JobModality.HYBRID,
        tags: ['Backend', 'APIs', 'Salud'],
        skills: ['Node.js', 'APIs REST', 'SQL'],
        applicantsCount: 10,
      },
      {
        slug: 'ux-healthcare-practicas-healthsync',
        title: 'UX para Salud Digital en Practicas',
        description: 'Colabora en flujos sencillos para pacientes y profesionales sanitarios.',
        overview: 'Rol para perfiles de diseno que quieren crear experiencias claras y accesibles.',
        modality: JobModality.HYBRID,
        tags: ['UX', 'Accesibilidad', 'Research'],
        skills: ['Figma', 'UX Research', 'Prototipado'],
        applicantsCount: 14,
      },
    ],
  },
  {
    slug: 'greengrid-energy',
    name: 'GreenGrid Energy',
    logoPhoto: 'photo-1509391366360-2e959784a276',
    bannerPhoto: 'photo-1473341304170-971dccb5ac1e',
    tagline: 'Energia limpia con datos y tecnologia',
    description: 'Empresa de energia renovable que usa software para optimizar instalaciones y consumo.',
    culture: 'Equipo tecnico con proposito sostenible, aprendizaje continuo y proyectos medibles.',
    location: 'Bilbao',
    size: '100-250 empleados',
    website: 'https://www.greengrid.example',
    industry: 'Energia renovable',
    foundedYear: 2016,
    tags: ['Sostenibilidad', 'Datos', 'IoT'],
    benefits: ['Proyectos con impacto', 'Mentoria tecnica', 'Horario flexible'],
    jobs: [
      {
        slug: 'datos-energia-practicas-greengrid',
        title: 'Analista de Datos Energeticos',
        description: 'Analiza consumo, produccion y rendimiento de instalaciones renovables.',
        overview: 'Practica para combinar datos, sostenibilidad y visualizacion de indicadores.',
        modality: JobModality.HYBRID,
        tags: ['Datos', 'Energia', 'Sostenibilidad'],
        skills: ['Excel', 'SQL', 'Power BI'],
        applicantsCount: 13,
      },
      {
        slug: 'web-sostenibilidad-practicas-greengrid',
        title: 'Desarrollador Web de Sostenibilidad',
        description: 'Apoya paneles web para seguimiento de instalaciones y reportes de impacto.',
        overview: 'Rol frontend para proyectos relacionados con energia limpia.',
        modality: JobModality.REMOTE,
        tags: ['Frontend', 'React', 'Sostenibilidad'],
        skills: ['React', 'JavaScript', 'CSS'],
        applicantsCount: 7,
      },
    ],
  },
  {
    slug: 'retailcraft-commerce',
    name: 'RetailCraft Commerce',
    logoPhoto: 'photo-1556742049-0cfed4f6a45d',
    bannerPhoto: 'photo-1556742502-ec7c0e9f34b1',
    tagline: 'Ecommerce pensado para vender mejor',
    description: 'Agencia especializada en tiendas online, automatizacion comercial y experiencia de compra.',
    culture: 'Ritmo dinamico, aprendizaje con clientes reales y mucha colaboracion entre diseno y desarrollo.',
    location: 'Zaragoza',
    size: '25-50 empleados',
    website: 'https://www.retailcraft.example',
    industry: 'Ecommerce',
    foundedYear: 2018,
    tags: ['Ecommerce', 'Marketing', 'Frontend'],
    benefits: ['Portfolio real', 'Mentoria en ecommerce', 'Equipo cercano'],
    jobs: [
      {
        slug: 'frontend-ecommerce-practicas-retailcraft',
        title: 'Frontend Ecommerce en Practicas',
        description: 'Construye secciones de tienda, fichas de producto y mejoras visuales.',
        overview: 'Practica para aprender frontend aplicado a conversion y experiencia de compra.',
        modality: JobModality.HYBRID,
        tags: ['Ecommerce', 'Frontend', 'React'],
        skills: ['React', 'CSS', 'Responsive'],
        applicantsCount: 15,
        featured: true,
      },
      {
        slug: 'marketing-automation-retailcraft',
        title: 'Marketing Automation Junior',
        description: 'Configura campanas, segmentaciones y reportes basicos de clientes.',
        overview: 'Rol orientado a automatizacion, datos comerciales y comunicacion digital.',
        modality: JobModality.REMOTE,
        tags: ['Marketing', 'CRM', 'Automatizacion'],
        skills: ['CRM', 'Email marketing', 'Analisis'],
        applicantsCount: 10,
      },
    ],
  },
  {
    slug: 'mobilityhub',
    name: 'MobilityHub',
    logoPhoto: 'photo-1519003722824-194d4455a60c',
    bannerPhoto: 'photo-1500530855697-b586d89ba3ee',
    tagline: 'Movilidad urbana conectada',
    description: 'Startup que desarrolla soluciones para gestionar flotas, rutas y movilidad compartida.',
    culture: 'Equipo agil, orientado a producto y con pruebas constantes sobre necesidades reales.',
    location: 'Malaga',
    size: '50-100 empleados',
    website: 'https://www.mobilityhub.example',
    industry: 'Movilidad',
    foundedYear: 2021,
    tags: ['Movilidad', 'Producto', 'Apps'],
    benefits: ['Mentoria de producto', 'Trabajo hibrido', 'Aprendizaje rapido'],
    jobs: [
      {
        slug: 'mobile-app-practicas-mobilityhub',
        title: 'Desarrollador Mobile Junior',
        description: 'Apoya funcionalidades de apps de movilidad y pruebas de experiencia de usuario.',
        overview: 'Practica para estudiantes con interes en aplicaciones moviles y producto digital.',
        modality: JobModality.HYBRID,
        tags: ['Mobile', 'Apps', 'Producto'],
        skills: ['React Native', 'JavaScript', 'UX basico'],
        applicantsCount: 18,
      },
      {
        slug: 'operaciones-digitales-mobilityhub',
        title: 'Asistente de Operaciones Digitales',
        description: 'Revisa incidencias, datos de rutas y documentacion de procesos internos.',
        overview: 'Rol practico para entender operaciones, datos y soporte en producto digital.',
        modality: JobModality.ONSITE,
        tags: ['Operaciones', 'Datos', 'Soporte'],
        skills: ['Excel', 'Comunicacion', 'Analisis'],
        applicantsCount: 6,
      },
    ],
  },
  {
    slug: 'securewave-cybersecurity',
    name: 'SecureWave Cybersecurity',
    logoPhoto: 'photo-1550751827-4bd374c3f58b',
    bannerPhoto: 'photo-1563986768609-322da13575f3',
    tagline: 'Proteccion digital para empresas',
    description: 'Consultora de ciberseguridad especializada en auditorias, monitorizacion y formacion.',
    culture: 'Cultura tecnica, discreta y orientada a aprendizaje responsable.',
    location: 'Madrid',
    size: '100-250 empleados',
    website: 'https://www.securewave.example',
    industry: 'Ciberseguridad',
    foundedYear: 2016,
    tags: ['Seguridad', 'Sistemas', 'Remoto'],
    benefits: ['Formacion en seguridad', 'Mentoria tecnica', 'Certificaciones internas'],
    jobs: [
      {
        slug: 'analista-ciberseguridad-practicas-securewave',
        title: 'Analista de Ciberseguridad en Practicas',
        description: 'Apoya tareas de revision, documentacion de riesgos y analisis de alertas.',
        overview: 'Practica para perfiles con interes en seguridad defensiva y buenas practicas.',
        modality: JobModality.HYBRID,
        tags: ['Ciberseguridad', 'SOC', 'Sistemas'],
        skills: ['Linux', 'Redes', 'Seguridad'],
        applicantsCount: 22,
        featured: true,
      },
      {
        slug: 'automatizacion-seguridad-securewave',
        title: 'Automatizacion de Seguridad Junior',
        description: 'Crea scripts sencillos para automatizar revisiones y reportes tecnicos.',
        overview: 'Rol tecnico para aprender automatizacion aplicada a ciberseguridad.',
        modality: JobModality.REMOTE,
        tags: ['Automatizacion', 'Python', 'Seguridad'],
        skills: ['Python', 'Linux', 'Git'],
        applicantsCount: 12,
      },
    ],
  },
  {
    slug: 'travelnest-digital',
    name: 'TravelNest Digital',
    logoPhoto: 'photo-1507525428034-b723cf961d3e',
    bannerPhoto: 'photo-1488646953014-85cb44e25828',
    tagline: 'Experiencias de viaje con tecnologia',
    description: 'Plataforma de turismo digital para reservas, recomendaciones y gestion de experiencias.',
    culture: 'Equipo creativo, internacional y orientado a mejorar la experiencia del usuario.',
    location: 'Palma',
    size: '50-100 empleados',
    website: 'https://www.travelnest.example',
    industry: 'Turismo digital',
    foundedYear: 2019,
    tags: ['Turismo', 'Producto', 'Marketing'],
    benefits: ['Equipo internacional', 'Mentoria de producto', 'Horario flexible'],
    jobs: [
      {
        slug: 'product-tourism-practicas-travelnest',
        title: 'Asistente de Producto Turistico',
        description: 'Colabora en mejoras de experiencia, analisis de usuarios y priorizacion de funcionalidades.',
        overview: 'Practica para aprender producto digital en el sector turistico.',
        modality: JobModality.HYBRID,
        tags: ['Producto', 'Turismo', 'UX'],
        skills: ['Analisis', 'Figma', 'Comunicacion'],
        applicantsCount: 11,
      },
      {
        slug: 'seo-content-travelnest',
        title: 'SEO Content Junior',
        description: 'Apoya contenidos, investigacion de palabras clave y mejoras de posicionamiento.',
        overview: 'Rol para perfiles con interes en marketing digital y contenido.',
        modality: JobModality.REMOTE,
        tags: ['SEO', 'Contenido', 'Marketing'],
        skills: ['SEO', 'Redaccion', 'Analytics'],
        applicantsCount: 17,
      },
    ],
  },
  {
    slug: 'agrosmart-tech',
    name: 'AgroSmart Tech',
    logoPhoto: 'photo-1500937386664-56d1dfef3854',
    bannerPhoto: 'photo-1464226184884-fa280b87c399',
    tagline: 'Tecnologia para el campo conectado',
    description: 'Agrotech que aplica sensores, datos y software para optimizar cultivos.',
    culture: 'Trabajo aplicado, visitas puntuales a campo y colaboracion entre tecnologia y negocio.',
    location: 'Murcia',
    size: '25-50 empleados',
    website: 'https://www.agrosmart.example',
    industry: 'AgroTech',
    foundedYear: 2020,
    tags: ['IoT', 'Datos', 'Sostenibilidad'],
    benefits: ['Proyectos reales', 'Mentoria tecnica', 'Aprendizaje sectorial'],
    jobs: [
      {
        slug: 'iot-agrotech-practicas-agrosmart',
        title: 'Asistente IoT AgroTech',
        description: 'Apoya el seguimiento de sensores, incidencias y paneles de monitorizacion.',
        overview: 'Practica para aprender IoT aplicado a agricultura y datos ambientales.',
        modality: JobModality.HYBRID,
        tags: ['IoT', 'Sensores', 'Datos'],
        skills: ['IoT', 'Excel', 'SQL basico'],
        applicantsCount: 8,
      },
      {
        slug: 'data-agri-practicas-agrosmart',
        title: 'Analista de Datos Agricolas',
        description: 'Trabaja con datos de riego, clima y rendimiento para generar informes utiles.',
        overview: 'Rol orientado a analisis de datos en proyectos de sostenibilidad agricola.',
        modality: JobModality.HYBRID,
        tags: ['Datos', 'Agricultura', 'Reporting'],
        skills: ['Power BI', 'Excel', 'Analisis'],
        applicantsCount: 5,
      },
    ],
  },
  {
    slug: 'legaltechia',
    name: 'LegalTechia',
    logoPhoto: 'photo-1589829545856-d10d557cf95f',
    bannerPhoto: 'photo-1521791055366-0d553872125f',
    tagline: 'Herramientas legales mas simples',
    description: 'Legaltech enfocada en automatizacion documental, gestion de expedientes y firma digital.',
    culture: 'Trabajo ordenado, documentacion precisa y mejora continua de procesos.',
    location: 'Madrid',
    size: '25-50 empleados',
    website: 'https://www.legaltechia.example',
    industry: 'LegalTech',
    foundedYear: 2018,
    tags: ['LegalTech', 'Automatizacion', 'SaaS'],
    benefits: ['Mentoria funcional', 'Trabajo hibrido', 'Aprendizaje en SaaS'],
    jobs: [
      {
        slug: 'frontend-legaltech-practicas-legaltechia',
        title: 'Frontend LegalTech en Practicas',
        description: 'Crea pantallas y formularios para gestion documental y firma digital.',
        overview: 'Practica frontend dentro de un producto SaaS con flujos de negocio reales.',
        modality: JobModality.HYBRID,
        tags: ['Frontend', 'SaaS', 'LegalTech'],
        skills: ['React', 'Forms', 'CSS'],
        applicantsCount: 9,
      },
      {
        slug: 'automatizacion-documental-legaltechia',
        title: 'Automatizacion Documental Junior',
        description: 'Apoya plantillas, reglas de negocio y pruebas de generacion documental.',
        overview: 'Rol para aprender automatizacion y procesos documentales en producto legal.',
        modality: JobModality.REMOTE,
        tags: ['Automatizacion', 'Documentacion', 'QA'],
        skills: ['Excel', 'Testing', 'Logica'],
        applicantsCount: 6,
      },
    ],
  },
  {
    slug: 'mediaforge-studio',
    name: 'MediaForge Studio',
    logoPhoto: 'photo-1492724441997-5dc865305da7',
    bannerPhoto: 'photo-1516321318423-f06f85e504b3',
    tagline: 'Contenido digital con enfoque de marca',
    description: 'Estudio creativo que produce contenidos, campanas y piezas digitales para marcas.',
    culture: 'Ambiente creativo, proyectos variados y feedback constante sobre portfolio.',
    location: 'Barcelona',
    size: '10-25 empleados',
    website: 'https://www.mediaforge.example',
    industry: 'Contenido digital',
    foundedYear: 2022,
    tags: ['Contenido', 'Diseno', 'Marketing'],
    benefits: ['Portfolio real', 'Mentoria creativa', 'Equipo cercano'],
    jobs: [
      {
        slug: 'content-producer-practicas-mediaforge',
        title: 'Content Producer en Practicas',
        description: 'Ayuda a planificar, crear y publicar piezas de contenido para marcas.',
        overview: 'Practica creativa para aprender flujos de contenido digital profesional.',
        modality: JobModality.HYBRID,
        tags: ['Contenido', 'Social Media', 'Marca'],
        skills: ['Redaccion', 'Canva', 'Planificacion'],
        applicantsCount: 14,
      },
      {
        slug: 'diseno-digital-practicas-mediaforge',
        title: 'Diseno Digital Junior',
        description: 'Crea piezas visuales para redes, presentaciones y campanas digitales.',
        overview: 'Rol orientado a portfolio visual y trabajo con briefings reales.',
        modality: JobModality.ONSITE,
        tags: ['Diseno', 'Branding', 'Creatividad'],
        skills: ['Figma', 'Photoshop', 'Branding'],
        applicantsCount: 20,
        featured: true,
      },
    ],
  },
  {
    slug: 'peopleops-lab',
    name: 'PeopleOps Lab',
    logoPhoto: 'photo-1551836022-d5d88e9218df',
    bannerPhoto: 'photo-1556761175-b413da4baf72',
    tagline: 'Gestion de talento con datos',
    description: 'HR tech que ayuda a empresas a gestionar seleccion, clima y desarrollo profesional.',
    culture: 'Comunicacion cercana, sensibilidad por personas y trabajo basado en datos.',
    location: 'Sevilla',
    size: '25-50 empleados',
    website: 'https://www.peopleopslab.example',
    industry: 'HR Tech',
    foundedYear: 2021,
    tags: ['RRHH', 'Datos', 'Producto'],
    benefits: ['Mentoria en talento', 'Trabajo hibrido', 'Formacion en producto'],
    jobs: [
      {
        slug: 'people-analytics-practicas-peopleops',
        title: 'People Analytics en Practicas',
        description: 'Analiza datos de procesos de seleccion, clima y seguimiento de talento.',
        overview: 'Practica para aprender analitica aplicada a recursos humanos.',
        modality: JobModality.HYBRID,
        tags: ['RRHH', 'Datos', 'Analytics'],
        skills: ['Excel', 'Power BI', 'Comunicacion'],
        applicantsCount: 7,
      },
      {
        slug: 'employer-branding-peopleops',
        title: 'Employer Branding Junior',
        description: 'Apoya contenidos, campanas y materiales para atraer talento.',
        overview: 'Rol para perfiles con interes en comunicacion, marca y personas.',
        modality: JobModality.REMOTE,
        tags: ['Marca', 'RRHH', 'Contenido'],
        skills: ['Redaccion', 'Canva', 'Marketing'],
        applicantsCount: 12,
      },
    ],
  },
  {
    slug: 'urbandata-cities',
    name: 'UrbanData Cities',
    logoPhoto: 'photo-1486406146926-c627a92ad1ab',
    bannerPhoto: 'photo-1518005020951-eccb494ad742',
    tagline: 'Ciudades inteligentes con informacion util',
    description: 'Empresa que crea soluciones de datos, mapas y analisis para administraciones locales.',
    culture: 'Equipo multidisciplinar, proyectos publicos y foco en accesibilidad de la informacion.',
    location: 'Valencia',
    size: '50-100 empleados',
    website: 'https://www.urbandata.example',
    industry: 'Smart Cities',
    foundedYear: 2017,
    tags: ['Smart Cities', 'Datos', 'Mapas'],
    benefits: ['Proyectos publicos', 'Mentoria tecnica', 'Trabajo hibrido'],
    jobs: [
      {
        slug: 'data-smart-cities-urbandata',
        title: 'Analista de Datos Urbanos',
        description: 'Apoya informes y visualizaciones sobre movilidad, servicios y actividad urbana.',
        overview: 'Practica para trabajar con datos urbanos y cuadros de mando publicos.',
        modality: JobModality.HYBRID,
        tags: ['Datos', 'Ciudad', 'BI'],
        skills: ['SQL', 'Power BI', 'Analisis'],
        applicantsCount: 10,
      },
      {
        slug: 'gis-frontend-urbandata',
        title: 'Frontend GIS en Practicas',
        description: 'Colabora en interfaces con mapas, filtros y visualizacion geografica.',
        overview: 'Rol frontend para perfiles interesados en mapas y datos territoriales.',
        modality: JobModality.HYBRID,
        tags: ['Frontend', 'Mapas', 'GIS'],
        skills: ['JavaScript', 'Mapas', 'CSS'],
        applicantsCount: 9,
      },
    ],
  },
  {
    slug: 'bionova-labs',
    name: 'BioNova Labs',
    logoPhoto: 'photo-1532187863486-abf9dbad1b69',
    bannerPhoto: 'photo-1580894894513-541e068a3e2b',
    tagline: 'Innovacion bio con soporte digital',
    description: 'Laboratorio biotecnologico que desarrolla herramientas internas para gestion y analisis de datos.',
    culture: 'Rigor, documentacion cuidada y colaboracion entre perfiles cientificos y tecnologicos.',
    location: 'Granada',
    size: '50-100 empleados',
    website: 'https://www.bionova.example',
    industry: 'Biotecnologia',
    foundedYear: 2015,
    tags: ['Biotech', 'Datos', 'Software'],
    benefits: ['Mentoria tecnica', 'Formacion sectorial', 'Proyectos internos'],
    jobs: [
      {
        slug: 'software-lab-practicas-bionova',
        title: 'Software de Laboratorio Junior',
        description: 'Apoya herramientas internas para registro, seguimiento y consulta de datos.',
        overview: 'Practica para aprender software aplicado a procesos de laboratorio.',
        modality: JobModality.HYBRID,
        tags: ['Software', 'Laboratorio', 'Backend'],
        skills: ['Node.js', 'SQL', 'Documentacion'],
        applicantsCount: 8,
      },
      {
        slug: 'data-quality-bionova',
        title: 'Data Quality en Practicas',
        description: 'Revisa datos internos, detecta inconsistencias y prepara reportes de calidad.',
        overview: 'Rol orientado a calidad de datos y procesos documentados.',
        modality: JobModality.ONSITE,
        tags: ['Datos', 'Calidad', 'Reporting'],
        skills: ['Excel', 'SQL basico', 'Analisis'],
        applicantsCount: 4,
      },
    ],
  },
  {
    slug: 'appworks-factory',
    name: 'AppWorks Factory',
    logoPhoto: 'photo-1519389950473-47ba0277781c',
    bannerPhoto: 'photo-1497366754035-f200968a6e72',
    tagline: 'Aplicaciones web a medida',
    description: 'Software factory que construye aplicaciones web para startups, pymes y equipos internos.',
    culture: 'Buenas practicas, code reviews y acompanamiento tecnico desde el primer dia.',
    location: 'Alicante',
    size: '50-100 empleados',
    website: 'https://www.appworks.example',
    industry: 'Desarrollo web',
    foundedYear: 2018,
    tags: ['Desarrollo', 'Full Stack', 'SaaS'],
    benefits: ['Code reviews', 'Mentoria full stack', 'Proyectos reales'],
    jobs: [
      {
        slug: 'react-developer-practicas-appworks',
        title: 'React Developer en Practicas',
        description: 'Desarrolla componentes, formularios y pantallas para aplicaciones cliente.',
        overview: 'Practica frontend para consolidar React y buenas practicas de UI.',
        modality: JobModality.HYBRID,
        tags: ['React', 'Frontend', 'JavaScript'],
        skills: ['React', 'CSS', 'Git'],
        applicantsCount: 24,
        featured: true,
      },
      {
        slug: 'api-integrations-practicas-appworks',
        title: 'Integraciones API Junior',
        description: 'Apoya conexiones con APIs externas, pruebas y documentacion tecnica.',
        overview: 'Rol para aprender backend ligero, integraciones y pruebas con Postman.',
        modality: JobModality.REMOTE,
        tags: ['APIs', 'Backend', 'Postman'],
        skills: ['Node.js', 'Postman', 'SQL'],
        applicantsCount: 13,
      },
    ],
  },
  {
    slug: 'marketpilot',
    name: 'MarketPilot',
    logoPhoto: 'photo-1460925895917-afdab827c52f',
    bannerPhoto: 'photo-1553028826-f4804a6dba3b',
    tagline: 'Marketing digital guiado por datos',
    description: 'Agencia data-driven especializada en campanas, CRM y optimizacion de conversion.',
    culture: 'Experimentacion controlada, medicion constante y aprendizaje por campanas reales.',
    location: 'Madrid',
    size: '25-50 empleados',
    website: 'https://www.marketpilot.example',
    industry: 'Marketing digital',
    foundedYear: 2020,
    tags: ['Marketing', 'Datos', 'CRM'],
    benefits: ['Mentoria en marketing', 'Campanas reales', 'Horario flexible'],
    jobs: [
      {
        slug: 'crm-marketing-practicas-marketpilot',
        title: 'CRM Marketing en Practicas',
        description: 'Configura segmentaciones, automatizaciones y reportes de campanas.',
        overview: 'Practica para aprender marketing operativo con datos y herramientas CRM.',
        modality: JobModality.REMOTE,
        tags: ['CRM', 'Marketing', 'Automatizacion'],
        skills: ['CRM', 'Email marketing', 'Excel'],
        applicantsCount: 16,
      },
      {
        slug: 'growth-analyst-practicas-marketpilot',
        title: 'Growth Analyst Junior',
        description: 'Analiza resultados de campanas, conversiones y oportunidades de mejora.',
        overview: 'Rol orientado a analisis, experimentacion y mejora de conversion.',
        modality: JobModality.HYBRID,
        tags: ['Growth', 'Analytics', 'Marketing'],
        skills: ['Analytics', 'Excel', 'Looker Studio'],
        applicantsCount: 18,
      },
    ],
  },
  {
    slug: 'solarmind',
    name: 'SolarMind',
    logoPhoto: 'photo-1497440001374-f26997328c1b',
    bannerPhoto: 'photo-1508514177221-188b1cf16e9d',
    tagline: 'Software para energia solar',
    description: 'Empresa que desarrolla herramientas para simular, vender y gestionar instalaciones solares.',
    culture: 'Equipo tecnico con foco en impacto, producto claro y aprendizaje compartido.',
    location: 'Cordoba',
    size: '25-50 empleados',
    website: 'https://www.solarmind.example',
    industry: 'Energia solar',
    foundedYear: 2019,
    tags: ['Solar', 'Producto', 'Datos'],
    benefits: ['Proyectos con impacto', 'Mentoria tecnica', 'Horario flexible'],
    jobs: [
      {
        slug: 'solar-simulator-practicas-solarmind',
        title: 'Simulador Solar Junior',
        description: 'Apoya mejoras en simuladores de ahorro, produccion y configuracion de instalaciones.',
        overview: 'Practica tecnica para combinar producto, datos y energia solar.',
        modality: JobModality.HYBRID,
        tags: ['Producto', 'Datos', 'Energia'],
        skills: ['JavaScript', 'Excel', 'Analisis'],
        applicantsCount: 9,
      },
      {
        slug: 'support-dev-solarmind',
        title: 'Soporte Tecnico de Producto',
        description: 'Documenta incidencias, reproduce errores y ayuda a mejorar la experiencia del usuario.',
        overview: 'Rol practico para conocer producto digital desde soporte y calidad.',
        modality: JobModality.REMOTE,
        tags: ['Soporte', 'QA', 'Producto'],
        skills: ['Comunicacion', 'Testing', 'Documentacion'],
        applicantsCount: 5,
      },
    ],
  },
  {
    slug: 'civiccloud',
    name: 'CivicCloud',
    logoPhoto: 'photo-1521737604893-d14cc237f11d',
    bannerPhoto: 'photo-1517048676732-d65bc937f952',
    tagline: 'Servicios publicos digitales mas accesibles',
    description: 'SaaS para digitalizar tramites, portales y herramientas de atencion ciudadana.',
    culture: 'Equipo orientado a accesibilidad, claridad y servicio publico.',
    location: 'Valladolid',
    size: '50-100 empleados',
    website: 'https://www.civiccloud.example',
    industry: 'GovTech',
    foundedYear: 2017,
    tags: ['GovTech', 'Accesibilidad', 'SaaS'],
    benefits: ['Mentoria en accesibilidad', 'Trabajo hibrido', 'Proyectos publicos'],
    jobs: [
      {
        slug: 'frontend-govtech-practicas-civiccloud',
        title: 'Frontend GovTech en Practicas',
        description: 'Desarrolla pantallas claras para portales de tramites y atencion ciudadana.',
        overview: 'Practica frontend centrada en accesibilidad y servicios digitales.',
        modality: JobModality.HYBRID,
        tags: ['Frontend', 'Accesibilidad', 'SaaS'],
        skills: ['React', 'HTML semantico', 'CSS'],
        applicantsCount: 11,
      },
      {
        slug: 'qa-accesibilidad-civiccloud',
        title: 'QA de Accesibilidad Junior',
        description: 'Revisa interfaces, documenta problemas y valida mejoras de accesibilidad.',
        overview: 'Rol para aprender testing funcional y accesibilidad web.',
        modality: JobModality.REMOTE,
        tags: ['QA', 'Accesibilidad', 'Testing'],
        skills: ['Testing', 'Accesibilidad', 'Documentacion'],
        applicantsCount: 7,
      },
    ],
  },
  {
    slug: 'eventoria-tech',
    name: 'Eventoria Tech',
    logoPhoto: 'photo-1492684223066-81342ee5ff30',
    bannerPhoto: 'photo-1511578314322-379afb476865',
    tagline: 'Eventos mejor organizados con software',
    description: 'Plataforma para gestionar inscripciones, agendas, entradas y comunicacion de eventos.',
    culture: 'Equipo activo, producto muy visible y colaboracion cercana con clientes.',
    location: 'Barcelona',
    size: '25-50 empleados',
    website: 'https://www.eventoria.example',
    industry: 'EventTech',
    foundedYear: 2021,
    tags: ['Eventos', 'SaaS', 'Producto'],
    benefits: ['Proyectos visibles', 'Mentoria de producto', 'Trabajo hibrido'],
    jobs: [
      {
        slug: 'fullstack-eventtech-practicas-eventoria',
        title: 'Full Stack EventTech en Practicas',
        description: 'Apoya funcionalidades para inscripciones, agendas y paneles de organizador.',
        overview: 'Practica full stack en un SaaS con uso real por organizadores de eventos.',
        modality: JobModality.HYBRID,
        tags: ['Full Stack', 'SaaS', 'Eventos'],
        skills: ['React', 'Node.js', 'SQL'],
        applicantsCount: 21,
        featured: true,
      },
      {
        slug: 'community-ops-eventoria',
        title: 'Community Operations Junior',
        description: 'Ayuda a organizar soporte, comunicacion y seguimiento de eventos publicados.',
        overview: 'Rol para perfiles interesados en operaciones, comunidad y producto digital.',
        modality: JobModality.ONSITE,
        tags: ['Operaciones', 'Comunidad', 'Producto'],
        skills: ['Comunicacion', 'Excel', 'Organizacion'],
        applicantsCount: 10,
      },
    ],
  },
];

const buildDemoResponsibilities = (jobTitle, companyName) => [
  `Apoyar al equipo de ${companyName} en tareas relacionadas con ${jobTitle.toLowerCase()}.`,
  'Participar en reuniones de seguimiento y revision de entregables.',
  'Documentar avances, aprendizajes e incidencias detectadas durante la practica.',
  'Colaborar con perfiles de producto, diseno o tecnologia segun las necesidades del proyecto.',
];

const buildDemoRequirements = (skills) => [
  'Estudiante de formacion profesional, grado o bootcamp relacionado con el puesto.',
  `Conocimientos basicos de ${skills.slice(0, 2).join(' y ')}.`,
  'Ganas de aprender, comunicacion clara y actitud proactiva.',
];

const jobCategoryBySlug = {
  'practica-product-management-techvision': JobCategory.PRODUCT,
  'desarrollador-full-stack-junior-growthlabs': JobCategory.DEVELOPMENT,
  'disenador-ux-ui-practicas-designstudio': JobCategory.DESIGN,
  'practica-devops-cloudscale': JobCategory.CLOUD_DEVOPS,
  'analista-datos-practicas-datanova': JobCategory.DATA,
  'tecnico-bi-dashboard-datanova': JobCategory.DATA,
  'desarrollador-elearning-edunext': JobCategory.DEVELOPMENT,
  'asistente-contenido-digital-edunext': JobCategory.CONTENT,
  'frontend-fintech-practicas-finflow': JobCategory.DEVELOPMENT,
  'qa-fintech-practicas-finflow': JobCategory.QA,
  'backend-healthtech-practicas-healthsync': JobCategory.DEVELOPMENT,
  'ux-healthcare-practicas-healthsync': JobCategory.DESIGN,
  'datos-energia-practicas-greengrid': JobCategory.DATA,
  'web-sostenibilidad-practicas-greengrid': JobCategory.DEVELOPMENT,
  'frontend-ecommerce-practicas-retailcraft': JobCategory.DEVELOPMENT,
  'marketing-automation-retailcraft': JobCategory.MARKETING,
  'mobile-app-practicas-mobilityhub': JobCategory.DEVELOPMENT,
  'operaciones-digitales-mobilityhub': JobCategory.OPERATIONS,
  'analista-ciberseguridad-practicas-securewave': JobCategory.CYBERSECURITY,
  'automatizacion-seguridad-securewave': JobCategory.CYBERSECURITY,
  'product-tourism-practicas-travelnest': JobCategory.PRODUCT,
  'seo-content-travelnest': JobCategory.MARKETING,
  'iot-agrotech-practicas-agrosmart': JobCategory.DEVELOPMENT,
  'data-agri-practicas-agrosmart': JobCategory.DATA,
  'frontend-legaltech-practicas-legaltechia': JobCategory.DEVELOPMENT,
  'automatizacion-documental-legaltechia': JobCategory.OPERATIONS,
  'content-producer-practicas-mediaforge': JobCategory.CONTENT,
  'diseno-digital-practicas-mediaforge': JobCategory.DESIGN,
  'people-analytics-practicas-peopleops': JobCategory.DATA,
  'employer-branding-peopleops': JobCategory.MARKETING,
  'data-smart-cities-urbandata': JobCategory.DATA,
  'gis-frontend-urbandata': JobCategory.DEVELOPMENT,
  'software-lab-practicas-bionova': JobCategory.DEVELOPMENT,
  'data-quality-bionova': JobCategory.DATA,
  'react-developer-practicas-appworks': JobCategory.DEVELOPMENT,
  'api-integrations-practicas-appworks': JobCategory.DEVELOPMENT,
  'crm-marketing-practicas-marketpilot': JobCategory.MARKETING,
  'growth-analyst-practicas-marketpilot': JobCategory.MARKETING,
  'solar-simulator-practicas-solarmind': JobCategory.PRODUCT,
  'support-dev-solarmind': JobCategory.OPERATIONS,
  'frontend-govtech-practicas-civiccloud': JobCategory.DEVELOPMENT,
  'qa-accesibilidad-civiccloud': JobCategory.QA,
  'fullstack-eventtech-practicas-eventoria': JobCategory.DEVELOPMENT,
  'community-ops-eventoria': JobCategory.OPERATIONS,
};

function normalizeText(value) {
  return value
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase();
}

function inferJobCategory(job) {
  if (jobCategoryBySlug[job.slug]) return jobCategoryBySlug[job.slug];

  const text = normalizeText(
    [job.title, job.description, job.overview, ...(job.tags || []), ...(job.skills || [])].filter(Boolean).join(' '),
  );

  const hasAny = (keywords) => keywords.some((keyword) => text.includes(keyword));

  if (hasAny(['ciberseguridad', 'seguridad', 'soc', 'cybersecurity'])) return JobCategory.CYBERSECURITY;
  if (hasAny(['devops', 'cloud', 'ci/cd', 'linux'])) return JobCategory.CLOUD_DEVOPS;
  if (hasAny(['testing', 'qa', 'tester', 'calidad'])) return JobCategory.QA;
  if (hasAny(['operaciones', 'operations', 'soporte', 'comunidad'])) return JobCategory.OPERATIONS;
  if (hasAny(['contenido', 'content producer', 'social media'])) return JobCategory.CONTENT;
  if (hasAny(['producto', 'product management', 'product'])) return JobCategory.PRODUCT;
  if (hasAny(['diseno', 'ux', 'figma', 'branding'])) return JobCategory.DESIGN;
  if (hasAny(['marketing', 'seo', 'crm', 'growth', 'employer branding'])) return JobCategory.MARKETING;
  if (hasAny(['datos', 'data', 'bi', 'analytics', 'analitica', 'reporting'])) return JobCategory.DATA;

  return JobCategory.DEVELOPMENT;
}

companies.push(
  ...additionalCompanySeeds.map(({ jobs: _jobs, logoPhoto, bannerPhoto, ...company }) => ({
    ...company,
    logo: unsplashImage(logoPhoto, 200, 200),
    banner: unsplashImage(bannerPhoto, 1400, 400),
    gallery: [unsplashImage(bannerPhoto, 600, 400), unsplashImage(logoPhoto, 600, 400)],
  })),
);

jobs.push(
  ...additionalCompanySeeds.flatMap((company, companyIndex) =>
    company.jobs.map((job, jobIndex) => ({
      companySlug: company.slug,
      slug: job.slug,
      title: job.title,
      description: job.description,
      overview: job.overview,
      location: job.location ?? company.location,
      modality: job.modality,
      duration: job.duration ?? (jobIndex === 0 ? '6 meses' : '4 meses'),
      salaryLabel: job.salaryLabel ?? (jobIndex === 0 ? '750 EUR/mes' : '700 EUR/mes'),
      schedule: job.schedule ?? '20 horas semanales',
      startDate: job.startDate ?? (jobIndex === 0 ? 'Septiembre 2026' : 'Octubre 2026'),
      applicationDeadline: new Date(
        job.applicationDeadline ?? (jobIndex === 0 ? '2026-08-30T23:59:59.000Z' : '2026-09-20T23:59:59.000Z'),
      ),
      openings: job.openings ?? 1,
      applicantsCount: job.applicantsCount ?? companyIndex + jobIndex,
      featured: job.featured ?? false,
      tags: job.tags,
      responsibilities: job.responsibilities ?? buildDemoResponsibilities(job.title, company.name),
      requirements: job.requirements ?? buildDemoRequirements(job.skills),
      benefits: job.benefits ?? company.benefits,
      skills: job.skills,
    })),
  ),
);

jobs.forEach((job) => {
  job.category = job.category || inferJobCategory(job);
});

async function main() {
  const adminPasswordHash = await bcrypt.hash('Admin12345', 12);
  const eventoriaPasswordHash = await bcrypt.hash('Eventoria12345', 12);

  await prisma.user.upsert({
    where: { email: 'admin@talentbridge.local' },
    update: {
      firstName: 'Admin',
      lastName: 'TalentBridge',
      role: UserRole.ADMIN,
    },
    create: {
      email: 'admin@talentbridge.local',
      passwordHash: adminPasswordHash,
      firstName: 'Admin',
      lastName: 'TalentBridge',
      role: UserRole.ADMIN,
    },
  });

  const companyBySlug = {};

  for (const company of companies) {
    companyBySlug[company.slug] = await prisma.company.upsert({
      where: { slug: company.slug },
      update: company,
      create: company,
    });
  }

  const eventoriaUser = await prisma.user.upsert({
    where: { email: 'eventoria@talentbridge.local' },
    update: {
      passwordHash: eventoriaPasswordHash,
      firstName: 'Eventoria',
      lastName: 'Tech',
      role: UserRole.COMPANY,
    },
    create: {
      email: 'eventoria@talentbridge.local',
      passwordHash: eventoriaPasswordHash,
      firstName: 'Eventoria',
      lastName: 'Tech',
      role: UserRole.COMPANY,
    },
  });

  await prisma.company.updateMany({
    where: {
      ownerId: eventoriaUser.id,
      NOT: { slug: 'eventoria-tech' },
    },
    data: { ownerId: null },
  });

  await prisma.company.update({
    where: { slug: 'eventoria-tech' },
    data: {
      ownerId: eventoriaUser.id,
      status: CompanyStatus.APPROVED,
    },
  });

  for (const job of jobs) {
    const { companySlug, ...jobData } = job;
    const company = companyBySlug[companySlug];

    await prisma.job.upsert({
      where: { slug: job.slug },
      update: {
        ...jobData,
        companyId: company.id,
      },
      create: {
        ...jobData,
        companyId: company.id,
      },
    });
  }

  console.log(`Seed completed: ${companies.length} companies, ${jobs.length} jobs, 1 admin user and 1 company user.`);
}

main()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
